### ISSUE TITLE
Text color Support for custom (non-stock, non-AppCompat) TextView subclasses

### ISSUE THREAD

**Issue by bmbariah** [afollestad/aesthetic#15]
Hi, first thanks for this lib.

I have a CustomTextView that I'm using to change fonts and it simply doesn't respond to any color changes in textColor. Works perfectly when I remove the CustomTextView and use a normal TextView.

 As a temp workaround, I am using another library by chrisjenx called [Calligraphy](https://github.com/chrisjenx/Calligraphy) to have fonts as an xml attribute.

**Comment by afollestad** [comment]
Well, that's because Aesthetic replaces views with its own during inflation. 

I'll think of ways to support custom views.

**Comment by afollestad** [comment]
In release 0.3.1, I've made Aesthetic's custom views public. You can extend `AestheticTextView` instead of `TextView` in your custom view class. Checkout [Custom View Subclasses](https://github.com/afollestad/aesthetic#custom-view-subclasses).

Otherwise, I'd recommend [subscribing to properties](https://github.com/afollestad/aesthetic#retrieving-current-values) and manually updating the text color or whatever else.
