### ISSUE TITLE
Can't change other process activity theme

### ISSUE THREAD

**Issue by a1018875550** [afollestad/aesthetic#61]
I try this library for my project;I have a activity in other process, and it not changed when I change theme

**Comment by timusus** [comment]
All of the Aesthetic properties are stored on a single instance of `Aesthetic`. Each property is then persisted via Shared Preferences.

Singletons on Android cannot be accessed across processes, and SharedPreferences does not support use across multiple processes (see the [SharedPreferences docs](https://developer.android.com/reference/android/content/SharedPreferences.html))

So, Aesthetic can't/doesn't support persisting theme properties across processes. 

You might want to look into manually copying the values of one instance of Aesthetic to the other, using inter-process communication. See https://developer.android.com/guide/components/processes-and-threads.html#IPC

I can't speak for the author, but I would say this falls outside the scope of what this library is trying to achieve. It's probably a problem for you to solve within your app, rather than a general Aesthetic problem.
